### ISSUE TITLE
thumbnails http on https website

### ISSUE THREAD

**Issue by diehummel** [RebelCode/wp-rss-aggregator#2] opened 2019-02-04 09:49 UTC
Hi,

local thumbnails from cache folder als called with http even when the site uses https.

example from my sourcecode of the webpage:
`<div class="thumbnail-excerpt wprss-feed-thumbnail"><img src='http://domain.xx/wp-content/uploads/cache/remote/53695944.png' width='175' height='150' />`

br

**Comment by mecha** [comment] 2019-02-15 13:22
Hi @diehummel.

We're aware of this issue on sites using HTTPS and have gone through the entire plugin and all the addons to fix all URLs.

Unfortunately for the Excerpts & Thumbnails addon specifically, which seems to be what you're using, the problem is a bit more deeply rooted. We're working on solving this issue in the near future, so keep an eye out for the update. 👀

**Comment by diehummel** [comment] 2019-02-15 13:57
Hi, thanks for the answer.
Meanwhile i use the Plugin "SSL Insecure Content Fixer" :)

**Comment by mecha** [comment] 2021-03-15 11:28
This issue was addressed in an update for the Templates add-on.

**Closed as completed by mecha** 2021-03-15 11:28 UTC
